new

diff --git a/.github/workflows/flake8.yaml b/.github/workflows/flake8.yaml
--- a/.github/workflows/flake8.yaml
+++ b/.github/workflows/flake8.yaml
@@ -36,11 +36,18 @@ jobs:
         id: check-flake8
         run: echo ${{ steps.changed-files.outputs.files }} | grep -q . && exit 1 || exit 0
 
-      - name: Prevent push on issues  # 步骤7: 防止提交包含问题的代码
-        if: steps.check-flake8.outcome != 'success'
+      -name: Prevent push on issues
+        if: ${{ failure() }}  # 如果前一个步骤失败，则执行当前步骤
         run: |
           echo "::error::flake8 found issues. Please fix them before pushing."
           exit 1
+
+
+      # - name: Prevent push on issues  # 步骤7: 防止提交包含问题的代码
+      #   if: steps.check-flake8.outcome != 'success'
+      #   run: |
+      #     echo "::error::flake8 found issues. Please fix them before pushing."
+      #     exit 1
 
 
 
